### ISSUE TITLE
Username an Password

### ISSUE THREAD

**Issue by Systm21** [hobbyquaker/dashbutton2mqtt#1]
Hi Hobbyquaker,
is it possible to connect to an Broker with username:password?

I tried "-u mqtt://user:pass@localhost:1883" but won't work....

Thank you

**Comment by hobbyquaker** [comment]
Just published v2.0.0 with an up-to-date mqtt.js lib. This should fix this issue and allow auth via mqtt-url. Let me know if it works for you. If it still doesn't work please paste the output (start with `-v debug`).
